platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

target '07U17' do

pod 'Alamofire'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'LLCycleScrollView'
pod 'Kingfisher'
pod 'Reusable'
pod 'SnapKit'
pod 'Then'


end