use_frameworks!
inhibit_all_warnings!

target '8CubeRunner' do
    pod 'Cartography', :git => "https://github.com/robb/Cartography.git", :tag => '3.0.0'
    pod 'HTPressableButton', '~> 1.3.3'
    pod 'BitwiseFont', '~> 0.1.0'
    pod 'SwiftCubicSpline', '~> 0.1.0'
end