# Uncomment this line to define a global platform for your project
# platform :ios, '8.1'

target '3TodoList' do
    pod 'FontAwesomeKit', :git => "https://github.com/gscalzo/FontAwesomeKit.git"
    pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git" 
    pod 'Cartography', '~> 0.1'
    pod 'MGSwipeTableCell', '~> 1.3.5'
end

target '3TodoListTests' do

end

target '3TodoListUITests' do

end

